feat: add branch validation to release workflow

diff --git a/.github/workflows/build-release_to-branch.yaml b/.github/workflows/build-release_to-branch.yaml
--- a/.github/workflows/build-release_to-branch.yaml
+++ b/.github/workflows/build-release_to-branch.yaml
@@ -1,4 +1,4 @@
-name: Build Release
+name: Manual release by merging any branch into the default branch
 
 on:
   workflow_dispatch:
@@ -22,8 +22,22 @@ on:
         default: false
 
 jobs:
+  validate-branch:
+    runs-on: ubuntu-22.04
+    steps:
+      - name: Check if ref is default branch
+        if: ${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
+        run: |
+          target_branch="${{ github.ref }}"
+          default_branch="${{ github.event.repository.default_branch }}"
+          echo "::error::Cannot proceed on default branch. ($default_branch)"
+          echo "Target branch: $target_branch"
+          echo "Default branch: $default_branch"
+          exit 1
+
   update-packagejson:
-    uses: ./.github/workflows/reusable-update-packagejson.yaml
+    needs: [validate-branch]
+    uses: IShix-g/Unity-GitHubActions/.github/workflows/reusable-update-packagejson.yaml@main
     secrets:
       BOT_APP_ID: ${{ secrets.BOT_APP_ID }}
       BOT_PRIVATE_KEY: ${{ secrets.BOT_PRIVATE_KEY }}
@@ -34,9 +48,9 @@ jobs:
       dry-run: ${{ inputs.dry-run }}
 
   merge-and-push:
-    needs: [update-packagejson]
+    needs: [validate-branch, update-packagejson]
     if: ${{ needs.update-packagejson.outputs.changed == '1' }}
-    uses: ./.github/workflows/reusable-merge-and-push.yaml
+    uses: IShix-g/Unity-GitHubActions/.github/workflows/reusable-merge-and-push.yaml@main
     secrets:
       BOT_APP_ID: ${{ secrets.BOT_APP_ID }}
       BOT_PRIVATE_KEY: ${{ secrets.BOT_PRIVATE_KEY }}
@@ -48,7 +62,7 @@ jobs:
       fast-forward: ${{ inputs.fast-forward }}
 
   validate-outputs:
-    needs: [update-packagejson, merge-and-push]
+    needs: [validate-branch, update-packagejson, merge-and-push]
     if: ${{ needs.update-packagejson.outputs.changed != '1' || needs.merge-and-push.outputs.merged != '1' }}
     runs-on: ubuntu-22.04
     steps:
@@ -56,21 +70,20 @@ jobs:
         run: |
           target_branch="${{ needs.create-branches.outputs.target-branch }}"
           push_branch="${{ needs.create-branches.outputs.push-branch }}"
-          
           echo "::error::Conditions not met. Exiting..."
           echo "Target branch: $target_branch"
           echo "Push branch: $push_branch"
           exit 1
 
   release-notes:
-    needs: [update-packagejson, merge-and-push, validate-outputs]
-    uses: ./.github/workflows/reusable-release-notes.yaml
+    needs: [validate-branch, update-packagejson, merge-and-push, validate-outputs]
+    uses: IShix-g/Unity-GitHubActions/.github/workflows/reusable-release-notes.yaml@main
     with:
       commit-id: ${{ needs.update-packagejson.outputs.sha }}
 
   create-release:
-    needs: [update-packagejson, merge-and-push, validate-outputs, release-notes]
-    uses: ./.github/workflows/reusable-create-release.yaml
+    needs: [validate-branch, update-packagejson, merge-and-push, validate-outputs, release-notes]
+    uses: ./.github/workflows/reusable-create-release.yaml@main
     secrets:
       BOT_APP_ID: ${{ secrets.BOT_APP_ID }}
       BOT_PRIVATE_KEY: ${{ secrets.BOT_PRIVATE_KEY }}
@@ -81,9 +94,9 @@ jobs:
       release-note: ${{ needs.release-notes.outputs.notes }}
 
   clean-branch:
-    needs: [update-packagejson, merge-and-push, validate-outputs, release-notes, create-release]
+    needs: [validate-branch, update-packagejson, merge-and-push, validate-outputs, release-notes]
     if: ${{ inputs.clean-branch }}
-    uses: ./.github/workflows/reusable-clean-branch.yaml
+    uses: IShix-g/Unity-GitHubActions/.github/workflows/reusable-clean-branch.yaml@main
     secrets:
       BOT_APP_ID: ${{ secrets.BOT_APP_ID }}
       BOT_PRIVATE_KEY: ${{ secrets.BOT_PRIVATE_KEY }}
