Feature/create release (#171)
* feat: add check for existing tags before creating new ones

* fix: handle existing tags in release creation

* fix: remove unnecessary condition on tag creation step

* fix: use fallback for GH_TOKEN in reusable workflow

* fix: improve tag deletion handling in release workflow

diff --git a/.github/workflows/reusable-create-release.yaml b/.github/workflows/reusable-create-release.yaml
--- a/.github/workflows/reusable-create-release.yaml
+++ b/.github/workflows/reusable-create-release.yaml
@@ -87,11 +87,24 @@ jobs:
 
       - name: Delete Existing Tag
         env:
-          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          GH_TOKEN: ${{ steps.app-token.outputs.token || secrets.GITHUB_TOKEN }}
         run: |
-          echo "Tag '${{ inputs.tag }}' already exists. Deleting it..."
-          git tag -d ${{ inputs.tag }} || echo "Local tag not found."
-          git push --delete origin ${{ inputs.tag }}
+          tag=${{ inputs.tag }}
+          echo "Tag '$tag' already exists. Checking for deletion requirements..."
+          
+          if git ls-remote --tags origin $tag | grep -q $tag; then
+            echo "Remote tag '$tag' exists. Attempting to delete..."
+            git push --delete origin $tag && echo "Remote tag '$tag' deleted successfully." || echo "Failed to delete remote tag '$tag'."
+          else
+            echo "Remote tag '$tag' does not exist. Skipping remote deletion."
+          fi
+
+          if git tag -l | grep -q $tag; then
+            echo "Local tag '$tag' exists. Attempting to delete..."
+            git tag -d $tag && echo "Local tag '$tag' deleted successfully." || echo "Failed to delete local tag '$tag'."
+          else
+            echo "Local tag '$tag' does not exist. Skipping local deletion."
+          fi
 
       - name: Create Tag
         env:
