Feature/create release (#170)
* feat: add check for existing tags before creating new ones

* fix: handle existing tags in release creation

* fix: remove unnecessary condition on tag creation step

diff --git a/.github/workflows/reusable-create-release.yaml b/.github/workflows/reusable-create-release.yaml
--- a/.github/workflows/reusable-create-release.yaml
+++ b/.github/workflows/reusable-create-release.yaml
@@ -85,17 +85,15 @@ jobs:
         run: |
           git config --global url."https://x-access-token:${{ steps.app-token.outputs.token }}@github.com/".insteadOf "https://github.com/"
 
-      - name: Check if Tag Already Exists
-        id: check-tag
+      - name: Delete Existing Tag
         env:
           GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
-          if git ls-remote --tags origin ${{ inputs.tag }} | grep -q ${{ inputs.tag }}; then
-            echo "exists=1" >> "$GITHUB_OUTPUT"
-          fi
+          echo "Tag '${{ inputs.tag }}' already exists. Deleting it..."
+          git tag -d ${{ inputs.tag }} || echo "Local tag not found."
+          git push --delete origin ${{ inputs.tag }}
 
       - name: Create Tag
-        if: ${{ steps.check-tag.outputs.exists == '1' }}
         env:
           GH_TOKEN: ${{ steps.app-token.outputs.token || secrets.GITHUB_TOKEN }}
         run: |
