feat: improve tag creation process in release workflow

diff --git a/.github/workflows/reusable-create-release.yaml b/.github/workflows/reusable-create-release.yaml
--- a/.github/workflows/reusable-create-release.yaml
+++ b/.github/workflows/reusable-create-release.yaml
@@ -107,6 +107,13 @@ jobs:
           tag="${{ inputs.tag }}"
           commit_id="${{ inputs.commit-id }}"
 
+          echo "Fetching the latest tags to update cache..."
+          git fetch --tags || {
+            echo "::error::Failed to fetch tags. Exiting."
+            exit 1
+          }
+          git remote prune origin || echo "Failed to prune stale references; continuing..."
+
           if git rev-parse "$tag" >/dev/null 2>&1; then
             echo "Deleting existing local tag '$tag'..."
             git tag -d "$tag" || {
@@ -123,14 +130,15 @@ jobs:
           }
           echo "Successfully deleted the remote tag '$tag'."
 
+          echo "Creating new tag '$tag' for commit '$commit_id'..."
           git tag "$tag" "$commit_id" || {
             echo "::error::Unable to create the tag '$tag' on commit '$commit_id'. Exiting."
             exit 1
           }
           echo "Tag '$tag' created on commit '$commit_id'."
 
-          echo "Pushing new tag '$tag' to remote..."
-          git push origin "$tag" || {
+          echo "Force pushing the new tag '$tag' to remote..."
+          git push --force origin "$tag" || {
             echo "::error::Failed to push the updated tag '$tag' to remote. Exiting."
             exit 1
           }
